post_install() {
  if [[ -e '/opt/Qoder CN/chrome-sandbox' ]]; then
    chmod 0755 '/opt/Qoder CN/chrome-sandbox' || true
  fi
  command -v update-mime-database >/dev/null && update-mime-database /usr/share/mime || true
  command -v update-desktop-database >/dev/null && update-desktop-database /usr/share/applications || true
}

post_upgrade() {
  post_install
}

post_remove() {
  command -v update-mime-database >/dev/null && update-mime-database /usr/share/mime || true
  command -v update-desktop-database >/dev/null && update-desktop-database /usr/share/applications || true
}
